# -*- coding: utf-8 -*-
"""Day_1_App_Object_Detection_Yolo_PreTrained_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wdr1IwyCgISe_6-3-JGtxafJ81rXBPKD
"""

from ultralytics import YOLO
import gradio as gr
from PIL import Image
import numpy as np

model = YOLO("yolov8n.pt")

def detect_objects(image):
    if image is None:
        return None
    results = model.predict(source=image, save=False)
    result_img = results[0].plot()
    return Image.fromarray(result_img)

app = gr.Interface(
    fn=detect_objects,
    inputs=gr.Image(type="numpy", label="Upload Image"),
    outputs=gr.Image(type="pil", label="Detections"),
    title="My First Object Detection Project!",
    description="Hello! You can upload an image to see how the AI detects objects instantly.",
    allow_flagging="never"
)

app.launch(debug=True)