# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RFyNp3QuyE8UqhO3g52Ba4eT0fRLKKVS
"""

import ffmpeg
import os, tempfile, shutil
from ultralytics import YOLO
import gradio as gr

# Load YOLO model
model = YOLO("best.pt")

def detect_video(video_path):
    # Buat direktori temporer
    temp_dir = tempfile.mkdtemp()
    safe_name = os.path.basename(video_path).replace(" ", "_").replace("(", "").replace(")", "")
    safe_path = os.path.join(temp_dir, safe_name)
    shutil.copy(video_path, safe_path)

    # Jalankan YOLO
    model.predict(
        source=safe_path,
        save=True,
        project=temp_dir,
        name='output',
        exist_ok=True
    )

    # Cari hasil video
    output_folder = os.path.join(temp_dir, 'output')
    output_video = None
    for f in os.listdir(output_folder):
        if f.endswith('.avi') or f.endswith('.mp4'):
            output_video = os.path.join(output_folder, f)
            break

    if not output_video:
        return "⚠️ Tidak ditemukan hasil video."

    # Convert ke .mp4 jika masih .avi
    if output_video.endswith('.avi'):
        mp4_path = output_video.replace('.avi', '.mp4')
        ffmpeg.input(output_video).output(mp4_path, vcodec='libx264', acodec='aac').run(overwrite_output=True)
        output_video = mp4_path

    return output_video


# 🎨 Custom CSS
# 🎨 Custom CSS (centered title + larger text)
custom_css = """
body, .gradio-container {
    background-color: #001F3F !important;
}
h1, h2, h3, p, label {
    color: #ECF0F1 !important;
    font-family: 'Poppins', sans-serif;
}
h1 {
    text-align: center !important;
    font-size: 36px !important;
    font-weight: 700 !important;
    margin-bottom: 20px !important;
}
h2, h3, p, label {
    font-size: 18px !important;
}
button, .gr-button {
    background-color: white !important;
    color: #001F3F !important;
    border: 2px solid white !important;
    font-weight: bold !important;
    border-radius: 10px !important;
    font-size: 16px !important;
    transition: 0.3s;
}
button:hover, .gr-button:hover {
    background-color: #5DADE2 !important;
    color: white !important;
    border: 2px solid #5DADE2 !important;
}
"""

import ffmpeg
import os, tempfile, shutil
from ultralytics import YOLO
import gradio as gr

# Load YOLO model
model = YOLO("best.pt")

def detect_video(video_path):
    # Buat direktori temporer
    temp_dir = tempfile.mkdtemp()
    safe_name = os.path.basename(video_path).replace(" ", "_").replace("(", "").replace(")", "")
    safe_path = os.path.join(temp_dir, safe_name)
    shutil.copy(video_path, safe_path)

    # Jalankan YOLO
    model.predict(
        source=safe_path,
        save=True,
        project=temp_dir,
        name='output',
        exist_ok=True
    )

    # Cari hasil video
    output_folder = os.path.join(temp_dir, 'output')
    output_video = None
    for f in os.listdir(output_folder):
        if f.endswith('.avi') or f.endswith('.mp4'):
            output_video = os.path.join(output_folder, f)
            break

    if not output_video:
        return "⚠️ Tidak ditemukan hasil video."

    # Convert ke .mp4 jika masih .avi
    if output_video.endswith('.avi'):
        mp4_path = output_video.replace('.avi', '.mp4')
        ffmpeg.input(output_video).output(mp4_path, vcodec='libx264', acodec='aac').run(overwrite_output=True)
        output_video = mp4_path

    return output_video


# 🎨 Custom CSS (center title + bigger text)
custom_css = """
body, .gradio-container {
    background-color: #001F3F !important;
}
h1, h2, h3, p, label {
    color: #ECF0F1 !important;
    font-family: 'Poppins', sans-serif;
}
h1 {
    text-align: center !important;
    font-size: 36px !important;
    font-weight: 700 !important;
    margin-bottom: 20px !important;
}
h2, h3, p, label {
    font-size: 18px !important;
}
button, .gr-button {
    background-color: white !important;
    color: #001F3F !important;
    border: 2px solid white !important;
    font-weight: bold !important;
    border-radius: 10px !important;
    font-size: 16px !important;
    transition: 0.3s;
}
button:hover, .gr-button:hover {
    background-color: #5DADE2 !important;
    color: white !important;
    border: 2px solid #5DADE2 !important;
}
"""

# Jalankan Gradio
demo = gr.Interface(
    fn=detect_video,
    inputs=gr.Video(label="Upload your satellite footage below"),
    outputs=gr.Video(label="🛰️ Detection Result"),
    title="Satellite Detection",
    description="Upload your satellite footage and let the AI model detect objects automatically. Supported formats: .mp4, .avi, etc.",
    css=custom_css
)

demo.launch()